apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypostgres-deployment
  namespace: app
  labels:
    app: myapp
    type: db

spec:
  template:
    metadata:
      name: mypostgres-pod
      namespace: app
      labels:
        component: postgres
        app: myapp
        type: db
    spec:
      containers:
      - name: mypostgres-container
        image: postgres:alpine
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresvolume
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mypostgres-secret
                  key: PGPASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-app-configmap
                  key: PGDATABASE
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: my-app-configmap
                  key: PGUSER
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: my-app-configmap
                  key: PGHOST
      volumes:
        - name: postgresvolume
          persistentVolumeClaim:
            claimName: postgres-pvc
  replicas: 1
  selector:
    matchLabels:
      component: postgres
      app: myapp
      type: db