apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  namespace: app
  labels:
    component: postgres
    type: local
    app: myapp
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/reckony/Desktop/devops/projekt/webapp/k8s/data