apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynginx-replicaset
  namespace: app
  labels:
    component: web
    app: myapp

spec:
  template:
    metadata:
      name: mynginx-pod
      labels:
        component: web
        app: myapp
    spec:
      containers:
        - name: mynginx-container
          image: martal3szczynska/mynginx:latest
  replicas: 5
  selector:
    matchLabels:
      app: myapp
      component: web