apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
  namespace: app
  labels:
    component: web
    app: myapp

spec:
  template:
    metadata:
      name: mynginx-pod
      labels:
        component: web
        app: myapp
    spec:
      containers:
        - name: mynginx-container
          image: martal3szczynska/mynginx:latest

  replicas: 3
  selector:
    matchLabels:
      app: myapp
      component: web