kubectl delete ns app
kubectl delete ns ingress-nginx
kubectl delete services --all
kubectl delete configMaps --all
kubectl delete deployments --all
kubectl delete pods --all
kubectl delete ingresses --all
kubectl delete pvc --all
kubectl delete pv --all
kubectl delete secret --all
