version: '3'

#networks:
#    mymulticont:
#        name: mymulticont

services:
    myredis:
        image: 'redis:alpine'
        container_name: myredis
        depends_on:
            - mypostgres

    mypostgres:
        image: 'postgres:alpine'
        container_name: mypostgres
        environment:
          - POSTGRES_PASSWORD=1qaz2wsx
        volumes:
          - /Users/reckony/Desktop/devops/projekt/webapp/docker_project/postgresdata:/var/lib/postgresql/data

    mynginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '8080:80'

    backend:
        container_name: mybackend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - "/opt/myapp/node_modules"
            - ./backend:/opt/myapp
        ports:
            - '4000:4000'
        environment:
            - REDIS_HOST=myredis
            - REDIS_PORT=6379
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=mypostgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=1qaz2wsx
            - PGPORT=5432
        depends_on:
            - mypostgres
            - myredis
            - mynginx

    frontend:
        container_name: myfrontend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - "/opt/app/node_modules"
            - ./frontend:/opt/app
        environment:
            CHOKIDAR_USEPOLLING: "true"
        tty: true
        ports:
            - 3000:3000
        depends_on:
            - mypostgres
            - myredis
            - backend
            - mynginx