version: '3'

#networks:
#    mymulticont:
#        name: mymulticont

services:
    mypostgres:
        container_name: mypostgres
        image: 'postgres:alpine'
        environment:
          - POSTGRES_PASSWORD=1qaz2wsx
        volumes:
          - /Users/reckony/Desktop/devops/projekt/webapp/docker_project/postgresdata:/var/lib/postgresql/data

    myredis:
        container_name: myredis
        image: 'redis:alpine'
        depends_on:
            - mypostgres

    nginx:
        container_name: nginx
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '8080:80'

    backend:
        container_name: backend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - /opt/app/node_modules
            - ./backend:/opt/app

        ports:
            - '5000:5000'
        environment:
            - REDIS_HOST=myredis
            - REDIS_PORT=6379
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=mypostgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=1qaz2wsx
            - PGPORT=5432
        depends_on:
            - mypostgres
            - myredis
            - nginx

    frontend:
        container_name: frontend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /opt/app/node_modules
            - ./frontend:/opt/app
        environment:
            CHOKIDAR_USEPOLLING: "true"
        tty: true
        ports:
            - 3000:3000
        depends_on:
            - backend