#!/bin/sh

# docker stop mybackend
docker stop myredis
docker stop mypostgres
docker network rm my_app
docker rmi ml3szczynska/mywebapp

docker network create my_app
docker build . -t ml3szczynska/mywebapp
docker run -d --rm --network my_app --name myredis redis:alpine
docker run -d --rm --network my_app --name mypostgres -e POSTGRES_PASSWORD=1qaz2wsx -v /Users/reckony/Desktop/devops/projekt/postresdata:/var/lib/postgresql/data postgres:alpine
# docker run --rm --network my_app --name mywebapp -p 9090:9090 ml3szczynska/mywebapp

compose:

COMPOSE_HTTP_TIMEOUT=300 docker-compose up --build

curl:

curl --header "Content-Type: application/json" --request POST --data '{"name":"Ametyst","price":"25"}' http://localhost:8080/api/jewels
curl --header "Content-Type: application/json" --request POST --data '{"name":"Granat","price":"30"}' http://localhost:8080/api/jewels

curl --header "Content-Type: application/json" --request DELETE http://localhost:5000/jewels?id=1

curl --request GET http://localhost:5000/jewels