apiVersion: apps/v1
kind: Deployment
metadata:
  name: myredis-deployment
  namespace: app
  labels:
    app: myapp
    type: cache
    component: redis

spec:
  template:
    metadata:
      name: myredis-pod
      namespace: app
      labels:
        component: redis
        app: myapp
        type: cache
    spec:
      containers:
        - name: myredis-container
          image: redis:alpine
  replicas: 1 # was 3
  selector:
    matchLabels:
      component: redis
      app: myapp
      type: cache