apiVersion: v1
kind: Service

metadata:
    name: myredis-clusterip
    namespace: app
    labels:
        component: redis
        app: myapp

spec:
    type: ClusterIP
    ports:
        - targetPort: 6379
          port: 6379

    selector:
        app: myapp
        component: redis
        type: cache